[package]
name = "backoff"
version = "0.1.8"
edition = "2018"
authors = ["Tibor Benke <ihrwein@gmail.com>"]
license = "MIT/Apache-2.0"
readme = "README.md"
repository = "https://github.com/ihrwein/backoff"
homepage = "https://github.com/ihrwein/backoff"
documentation = "https://docs.rs/backoff"
categories = ["network-programming"]
description = """
Retry operations with exponential backoff policy.
"""

[badges]
travis-ci = { repository = "ihrwein/backoff" }

[dependencies]
async_std_1 = { package = "async-std", version = "1.6", optional = true }
futures-core = { version = "0.3.3", default-features = false, optional = true }
instant = "0.1"
pin-project = { version = "0.4.21", optional = true }
rand = "0.7"
tokio_02 = { package = "tokio", version = "0.2.21", features = ["time"], optional = true }

[dev-dependencies]
async_std_1 = { package = "async-std", version = "1.6", features = ["attributes"] }
reqwest = { version = "0.10.1", features = ["json", "blocking"] }
tokio_02 = { package = "tokio", version = "0.2.21", features = ["macros", "time"] }

[features]
default = []
stdweb = ["instant/stdweb", "rand/stdweb"]
wasm-bindgen = ["instant/wasm-bindgen", "rand/wasm-bindgen"]
tokio = ["futures-core", "pin-project", "tokio_02"]
async-std = ["async_std_1", "futures-core", "pin-project"]

[[example]]
name = "async"
required-features = ["tokio"]
